server:
  port: 8081

spring:
  application:
    name: site
  profiles:
    active: dev
  mvc:
    hiddenmethod:
      filter:
        enabled: true
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: prod